/// Enum com todos os municípios portugueses suportados pela API SAPO.
///
/// Uso:
/// ```dart
/// await getHolidaysByMunicipality(2026, Municipio.lisboa);
/// await getHolidaysByMunicipality(2026, Municipio.find('porto'));
/// ```
enum Municipio {
  abrantes('1401', 'Abrantes'),
  aguiarDaBeira('0901', 'Aguiar da Beira'),
  agueda('0101', 'Águeda'),
  albufeira('0801', 'Albufeira'),
  albergariaAVelha('0102', 'Albergaria-a-Velha'),
  alcanena('1402', 'Alcanena'),
  alcacerDoSal('1501', 'Alcácer do Sal'),
  alcochete('1502', 'Alcochete'),
  alcobaca('1001', 'Alcobaça'),
  alcoutim('0802', 'Alcoutim'),
  alenquer('1101', 'Alenquer'),
  alfandegaDaFe('0401', 'Alfândega da Fé'),
  aljezur('0803', 'Aljezur'),
  aljustrel('0201', 'Aljustrel'),
  almada('1503', 'Almada'),
  almeida('0902', 'Almeida'),
  almeirim('1403', 'Almeirim'),
  almodovar('0202', 'Almodôvar'),
  alpiarca('1404', 'Alpiarça'),
  alterDoChao('1201', 'Alter do Chão'),
  alvaiazere('1002', 'Alvaiázere'),
  alvito('0203', 'Alvito'),
  amadora('1115', 'Amadora'),
  amarante('1301', 'Amarante'),
  amares('0301', 'Amares'),
  anadia('0103', 'Anadia'),
  angraDoHeroismo('4301', 'Angra do Heroísmo'),
  ansiao('1003', 'Ansião'),
  arcosDeValdevez('1601', 'Arcos de Valdevez'),
  arganil('0601', 'Arganil'),
  armamar('1801', 'Armamar'),
  arouca('0104', 'Arouca'),
  arraiolos('0702', 'Arraiolos'),
  arronches('1202', 'Arronches'),
  arrudaDosVinhos('1102', 'Arruda dos Vinhos'),
  aveiro('0105', 'Aveiro'),
  avis('1203', 'Avis'),
  alandroal('0701', 'Alandroal'),
  azambuja('1103', 'Azambuja'),
  baiao('1302', 'Baião'),
  barcelos('0302', 'Barcelos'),
  barrancos('0204', 'Barrancos'),
  barreiro('1504', 'Barreiro'),
  batalha('1004', 'Batalha'),
  beja('0205', 'Beja'),
  belmonte('0501', 'Belmonte'),
  benavente('1405', 'Benavente'),
  bombarral('1005', 'Bombarral'),
  borba('0703', 'Borba'),
  boticas('1702', 'Boticas'),
  braga('0303', 'Braga'),
  braganca('0402', 'Bragança'),
  cabeceirasDeBasto('0304', 'Cabeceiras de Basto'),
  cadaval('1104', 'Cadaval'),
  caldasDaRainha('1006', 'Caldas da Rainha'),
  calhetaMadeira('3101', 'Calheta (Madeira)'),
  calhetaAcores('4501', 'Calheta (Açores)'),
  camaraDeLoboS('3102', 'Câmara de Lobos'),
  caminha('1602', 'Caminha'),
  campoMaior('1204', 'Campo Maior'),
  cantanhede('0602', 'Cantanhede'),
  carregalDoSal('1802', 'Carregal do Sal'),
  carrazedaDeAnsiaes('0403', 'Carrazeda de Ansiães'),
  cartaxo('1406', 'Cartaxo'),
  cascais('1105', 'Cascais'),
  castanheiraDePera('1007', 'Castanheira de Pêra'),
  casteloBranco('0502', 'Castelo Branco'),
  casteloDepAIva('0106', 'Castelo de Paiva'),
  casteloDeVide('1205', 'Castelo de Vide'),
  castroDaire('1803', 'Castro Daire'),
  castroMarim('0804', 'Castro Marim'),
  castroVerde('0206', 'Castro Verde'),
  celoricoDaBeira('0903', 'Celorico da Beira'),
  celoricoDeBasto('0305', 'Celorico de Basto'),
  chamusca('1407', 'Chamusca'),
  chaves('1703', 'Chaves'),
  cinfaes('1804', 'Cinfães'),
  coimbra('0603', 'Coimbra'),
  condeixaANova('0604', 'Condeixa-a-Nova'),
  constancia('1408', 'Constância'),
  coruche('1409', 'Coruche'),
  corvo('4901', 'Corvo'),
  covilha('0503', 'Covilhã'),
  crato('1206', 'Crato'),
  cuba('0207', 'Cuba'),
  elvas('1207', 'Elvas'),
  espinho('0107', 'Espinho'),
  esposende('0306', 'Esposende'),
  estarreja('0108', 'Estarreja'),
  estremoz('0704', 'Estremoz'),
  evora('0705', 'Évora'),
  fafe('0307', 'Fafe'),
  faro('0805', 'Faro'),
  felgueiras('1303', 'Felgueiras'),
  ferreiraDoAlentejo('0208', 'Ferreira do Alentejo'),
  ferreiraDoZezere('1411', 'Ferreira do Zêzere'),
  figueiraDaFoz('0605', 'Figueira da Foz'),
  figueiraDeCasteloRodrigo('0904', 'Figueira de Castelo Rodrigo'),
  figueiroDosVinhos('1008', 'Figueiró dos Vinhos'),
  fornosDeAlgodres('0905', 'Fornos de Algodres'),
  freixoDeEspadaACinta('0404', 'Freixo de Espada à Cinta'),
  fronteira('1208', 'Fronteira'),
  funchal('3103', 'Funchal'),
  fundao('0504', 'Fundão'),
  golega('1412', 'Golegã'),
  gondomar('1304', 'Gondomar'),
  gois('0606', 'Góis'),
  gouveia('0906', 'Gouveia'),
  grandola('1505', 'Grândola'),
  guimaraes('0308', 'Guimarães'),
  horta('4701', 'Horta'),
  idanhaANova('0505', 'Idanha-a-Nova'),
  ilhavo('0110', 'Ílhavo'),
  lagoaAlgarve('0806', 'Lagoa (Algarve)'),
  lagoaAcores('4201', 'Lagoa (Açores)'),
  lagos('0807', 'Lagos'),
  lamego('1805', 'Lamego'),
  lajesDasFlores('4801', 'Lajes das Flores'),
  lajesDoPico('4601', 'Lajes do Pico'),
  leiria('1009', 'Leiria'),
  lisboa('1106', 'Lisboa'),
  loule('0808', 'Loulé'),
  loures('1107', 'Loures'),
  lourinha('1108', 'Lourinhã'),
  lousa('0607', 'Lousã'),
  lousada('1305', 'Lousada'),
  macao('1413', 'Mação'),
  macedoDeCavaleiros('0405', 'Macedo de Cavaleiros'),
  machico('3104', 'Machico'),
  madalena('4602', 'Madalena'),
  mafra('1109', 'Mafra'),
  maia('1306', 'Maia'),
  mangualde('1806', 'Mangualde'),
  manteigas('0908', 'Manteigas'),
  marcoDeCanaveses('1307', 'Marco de Canaveses'),
  marinhaGrande('1010', 'Marinha Grande'),
  marvao('1210', 'Marvão'),
  matosinhos('1308', 'Matosinhos'),
  mealhada('0111', 'Mealhada'),
  melgaco('1603', 'Melgaço'),
  mertola('0209', 'Mértola'),
  mira('0608', 'Mira'),
  mirandaDoCorvo('0609', 'Miranda do Corvo'),
  mirandaDoDouro('0406', 'Miranda do Douro'),
  mirandela('0407', 'Mirandela'),
  mogadouro('0408', 'Mogadouro'),
  moita('1506', 'Moita'),
  moncao('1604', 'Monção'),
  monchique('0809', 'Monchique'),
  mondimDeBasto('1705', 'Mondim de Basto'),
  monforte('1211', 'Monforte'),
  montalegre('1706', 'Montalegre'),
  montemorONovo('0706', 'Montemor-o-Novo'),
  montemorOVelho('0610', 'Montemor-o-Velho'),
  montijo('1507', 'Montijo'),
  mora('0707', 'Mora'),
  mortagua('1808', 'Mortágua'),
  moura('0210', 'Moura'),
  mourao('0708', 'Mourão'),
  murca('1707', 'Murça'),
  murtosa('0112', 'Murtosa'),
  nazare('1011', 'Nazaré'),
  nelas('1809', 'Nelas'),
  nisa('1212', 'Nisa'),
  nordeste('4202', 'Nordeste'),
  obidos('1012', 'Óbidos'),
  odemira('0211', 'Odemira'),
  oeiras('1110', 'Oeiras'),
  oleiros('0506', 'Oleiros'),
  olhao('0810', 'Olhão'),
  oliveiraDeAzemeis('0113', 'Oliveira de Azeméis'),
  oliveiraDeFrades('1810', 'Oliveira de Frades'),
  oliveiraDoBairro('0114', 'Oliveira do Bairro'),
  oliveiraDoHospital('0611', 'Oliveira do Hospital'),
  ourem('1421', 'Ourém'),
  ourique('0212', 'Ourique'),
  ovar('0115', 'Ovar'),
  pacosDeFerreira('1309', 'Paços de Ferreira'),
  palmela('1508', 'Palmela'),
  pampilhosaDaSerra('0612', 'Pampilhosa da Serra'),
  paredes('1310', 'Paredes'),
  paredesDeCoura('1605', 'Paredes de Coura'),
  pedrogaoGrande('1013', 'Pedrógão Grande'),
  penacova('0613', 'Penacova'),
  penalvaDoCastelo('1811', 'Penalva do Castelo'),
  penamacor('0507', 'Penamacor'),
  penedono('1812', 'Penedono'),
  penela('0614', 'Penela'),
  peniche('1014', 'Peniche'),
  pesoDaRegua('1708', 'Peso da Régua'),
  pinhel('0910', 'Pinhel'),
  pontaDaRegua('1708', 'Peso da Régua'), // alias kept for safety
  pontaDeBarca('1606', 'Ponte da Barca'),
  pontaDeLima('1607', 'Ponte de Lima'),
  pontaDeSor('1213', 'Ponte de Sor'),
  pontaDelgada('4203', 'Ponta Delgada'),
  pontaDoSol('3105', 'Ponta do Sol'),
  portalegre('1214', 'Portalegre'),
  portel('0709', 'Portel'),
  porto('1312', 'Porto'),
  portoDeMos('1016', 'Porto de Mós'),
  portoMoniz('3106', 'Porto Moniz'),
  portoSanto('3201', 'Porto Santo'),
  povoaDeLanhoso('0309', 'Póvoa de Lanhoso'),
  povoaDeVarzim('1313', 'Póvoa de Varzim'),
  povoacao('4204', 'Povoação'),
  praiaDaVitoria('4302', 'Praia da Vitória'),
  proencaANova('0508', 'Proença-a-Nova'),
  redondo('0710', 'Redondo'),
  reguengosDeMonsaraz('0711', 'Reguengos de Monsaraz'),
  resende('1813', 'Resende'),
  ribeiraBrava('3107', 'Ribeira Brava'),
  ribeiraDePena('1709', 'Ribeira de Pena'),
  ribeiraGrande('4205', 'Ribeira Grande'),
  rioMaior('1414', 'Rio Maior'),
  sabrosa('1710', 'Sabrosa'),
  sabugal('0911', 'Sabugal'),
  salvaterraDeMagos('1415', 'Salvaterra de Magos'),
  santaCombaDao('1814', 'Santa Comba Dão'),
  santaCruz('3108', 'Santa Cruz'),
  santaCruzDaGraciosa('4401', 'Santa Cruz da Graciosa'),
  santaCruzDasFlores('4802', 'Santa Cruz das Flores'),
  santaMariaDaFeira('0109', 'Santa Maria da Feira'),
  santaMartaDePenaguiao('1711', 'Santa Marta de Penaguião'),
  santana('3109', 'Santana'),
  santarem('1416', 'Santarém'),
  santiagoDoCacem('1509', 'Santiago do Cacém'),
  santoTirso('1314', 'Santo Tirso'),
  saoBrasDeAlportel('0812', 'São Brás de Alportel'),
  saoJoaoDaMadeira('0116', 'São João da Madeira'),
  saoJoaoDaPesqueira('1815', 'São João da Pesqueira'),
  saoPedroDoSul('1816', 'São Pedro do Sul'),
  saoRoqueDoPico('4603', 'São Roque do Pico'),
  saoVicente('3110', 'São Vicente'),
  sardoal('1417', 'Sardoal'),
  satao('1817', 'Sátão'),
  seia('0912', 'Seia'),
  seixal('1510', 'Seixal'),
  sernancelhe('1818', 'Sernancelhe'),
  serta('0509', 'Sertã'),
  serpa('0213', 'Serpa'),
  sesimbra('1511', 'Sesimbra'),
  setubal('1512', 'Setúbal'),
  severDoVouga('0117', 'Sever do Vouga'),
  silves('0813', 'Silves'),
  sintra('1111', 'Sintra'),
  sobralDeMonteAgraco('1112', 'Sobral de Monte Agraço'),
  soure('0615', 'Soure'),
  sousel('1215', 'Sousel'),
  tabua('0616', 'Tábua'),
  tabuaco('1819', 'Tabuaço'),
  tarouca('1820', 'Tarouca'),
  tavira('0814', 'Tavira'),
  terrasDeBouro('0310', 'Terras de Bouro'),
  tomar('1418', 'Tomar'),
  tondela('1821', 'Tondela'),
  torreDeMoncorvo('0409', 'Torre de Moncorvo'),
  torresNovas('1419', 'Torres Novas'),
  torresVedras('1113', 'Torres Vedras'),
  trancoso('0913', 'Trancoso'),
  vagos('0118', 'Vagos'),
  valeDeCambra('0119', 'Vale de Cambra'),
  valenca('1608', 'Valença'),
  valongo('1315', 'Valongo'),
  velas('4502', 'Velas'),
  vendasNovas('0712', 'Vendas Novas'),
  vianaDoAlentejo('0713', 'Viana do Alentejo'),
  vianaDoCastelo('1609', 'Viana do Castelo'),
  vidigueira('0214', 'Vidigueira'),
  vieiraDoMinho('0311', 'Vieira do Minho'),
  vilaDeRei('0510', 'Vila de Rei'),
  vilaDoBispo('0815', 'Vila do Bispo'),
  vilaDoConde('1316', 'Vila do Conde'),
  vilaDoPorto('4101', 'Vila do Porto'),
  vilaFlor('0410', 'Vila Flor'),
  vilaFrancaDeXira('1114', 'Vila Franca de Xira'),
  vilaFrancaDoCampo('4206', 'Vila Franca do Campo'),
  vilaNovaDABarquinha('1420', 'Vila Nova da Barquinha'),
  vilaNovaDeCerveira('1610', 'Vila Nova de Cerveira'),
  vilaNovaDeEFamalicao('0312', 'Vila Nova de Famalicão'),
  vilaNovaDeEFozCoa('0914', 'Vila Nova de Foz Côa'),
  vilaNovaDeGaia('1317', 'Vila Nova de Gaia'),
  vilaNovaDePaiva('1822', 'Vila Nova de Paiva'),
  vilaNovaDePoiares('0617', 'Vila Nova de Poiares'),
  vilaPoucaDeAguiar('1713', 'Vila Pouca de Aguiar'),
  vilaReal('1714', 'Vila Real'),
  vilaRealDeSantoAntonio('0816', 'Vila Real de Santo António'),
  vilaVerde('0313', 'Vila Verde'),
  vilaVelhaDeRodao('0511', 'Vila Velha de Ródão'),
  vilaVicosa('0714', 'Vila Viçosa'),
  vimioso('0411', 'Vimioso'),
  vinhais('0413', 'Vinhais'),
  viseu('1823', 'Viseu'),
  vizela('0314', 'Vizela'),
  vouzela('1824', 'Vouzela');

  const Municipio(this.id, this.nome);

  /// ID SAPO do município.
  final String id;

  /// Nome oficial do município.
  final String nome;

  /// Encontra um [Municipio] pelo nome, sem distinguir maiúsculas ou acentos.
  ///
  /// Para homónimos usa o nome completo, ex: `'Lagoa (Algarve)'`.
  /// Lança [ArgumentError] se o município não for encontrado.
  static Municipio find(String nome) {
    final n = _normalise(nome);
    return Municipio.values.firstWhere(
      (m) => _normalise(m.nome) == n,
      orElse: () => throw ArgumentError.value(
        nome,
        'nome',
        'Município não encontrado. Usa Municipio.values para ver a lista completa.',
      ),
    );
  }
}

String _normalise(String s) => s
    .toLowerCase()
    .replaceAll('à', 'a')
    .replaceAll('á', 'a')
    .replaceAll('â', 'a')
    .replaceAll('ã', 'a')
    .replaceAll('ä', 'a')
    .replaceAll('ç', 'c')
    .replaceAll('é', 'e')
    .replaceAll('ê', 'e')
    .replaceAll('í', 'i')
    .replaceAll('ó', 'o')
    .replaceAll('ô', 'o')
    .replaceAll('õ', 'o')
    .replaceAll('ú', 'u')
    .replaceAll('ü', 'u')
    .trim();
